
USER_ROLE_TUTOR = "tutor"
USER_ROLE_STUDENT = "student"
USER_ROLE_ADMIN = "admin"

TUITION_STATUS_OPEN = "open"
TUITION_STATUS_ASSIGNED = "assigned"
TUITION_STATUS_COMPLETED = "completed"

APPLICATION_STATUS_PENDING = "pending"
APPLICATION_STATUS_ACCEPTED = "accepted"
APPLICATION_STATUS_REJECTED = "rejected"
